[0m14:09:22.857529 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025268B63040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002526B244A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002526B244880>]}


============================== 14:09:22.862729 | 783839ef-50cc-443d-ab72-86941685dafa ==============================
[0m14:09:22.862729 [info ] [MainThread]: Running with dbt=1.8.9
[0m14:09:22.863720 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Chinki Lengkong\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run -m base_olist__products', 'send_anonymous_usage_stats': 'True'}
[0m14:09:22.864721 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Chinki Lengkong\Documents\Projects\dbt-semantic-layer-implementation\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:09:22.865721 [debug] [MainThread]: Command `dbt run` failed at 14:09:22.865721 after 0.08 seconds
[0m14:09:22.866721 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025268B63040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002526B244880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002526B244B50>]}
[0m14:09:22.866721 [debug] [MainThread]: Flushing usage events
[0m14:09:24.434280 [debug] [MainThread]: An error was encountered while trying to flush usage events
